/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DeviceBox: typeof import('./src/components/Info/deviceBox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ForsetAndCity: typeof import('./src/components/ForsetAndCity.vue')['default']
    LoginBox: typeof import('./src/components/Login/loginBox.vue')['default']
    PlantDelegate: typeof import('./src/components/PlantDelegate.vue')['default']
    PlantDiversity: typeof import('./src/components/PlantDiversity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WhatIsForest: typeof import('./src/components/WhatIsForest.vue')['default']
  }
}
